#!/bin/sh

alaska=$(
	(
		ls /data/data/tiger/2006/www2.census.gov/geo/tiger/tiger2006se/AK/ |
		grep TGR |
		sed 's/.*TGR//' |
		sed 's/.ZIP//'

		ls /data/data/tiger/2013/www2.census.gov/geo/tiger/TIGERrd13/EDGES/tl_rd13_02* |
		sed 's/.*rd13_//' |
		sed 's/_edges.zip//'
	) | sort | uniq
)

./get-county-delta $alaska > county-delta/alaska

find /data/data/tiger/2006/www2.census.gov/geo/tiger/tiger2006se/ |
grep TGR |
sed 's/.*TGR//' |
sed 's/.ZIP//' |
grep -v '^02' |
sort |
xargs -P 8 -n 1 ./get-county-delta-wrap
