#!/usr/bin/perl

use utf8;

%state_number_map = (
	"01" => "AL", "02" => "AK", "04" => "AZ", "05" => "AR", "06" => "CA",
	"08" => "CO", "09" => "CT", "10" => "DE", "11" => "DC", "12" => "FL",
	"13" => "GA", "15" => "HI", "16" => "ID", "17" => "IL", "18" => "IN",
	"19" => "IA", "20" => "KS", "21" => "KY", "22" => "LA", "23" => "ME",
	"24" => "MD", "25" => "MA", "26" => "MI", "27" => "MN", "28" => "MS",
	"29" => "MO", "30" => "MT", "31" => "NE", "32" => "NV", "33" => "NH",
	"34" => "NJ", "35" => "NM", "36" => "NY", "37" => "NC", "38" => "ND",
	"39" => "OH", "40" => "OK", "41" => "OR", "42" => "PA", "44" => "RI",
	"45" => "SC", "46" => "SD", "47" => "TN", "48" => "TX", "49" => "UT",
	"50" => "VT", "51" => "VA", "53" => "WA", "54" => "WV", "55" => "WI",
	"56" => "WY", "60" => "AS", "66" => "GU", "69" => "MP", "72" => "PR",
	"78" => "VI",
);

%classes = (
	# http://wiki.openstreetmap.org/wiki/TIGER_2010

	"S1100" => "highway=motorway",
	"S1200" => "highway=primary",
	"S1400" => "highway=residential", # wiki says unclassified
	"S1500" => "highway=track",
	"S1630" => "highway=motorway_link",
	"S1640" => "highway=service",
	"S1710" => "highway=footway",
	"S1720" => "highway=steps",
	"S1730" => "highway=service",
	"S1740" => "highway=service",
	"S1780" => "highway=service",
	"S1820" => "highway=cycleway",
	"S1830" => "highway=bridleway",
	"R1011" => "railway=rail",
	"R1051" => "railway=light_rail",
	"R1052" => "railway=funicular",
);

open(IN, "tiger_abbrev.csv");
while (<IN>) {
	chomp;
	($code, $expanded) = split(/,/);
	$abbrev_typ{$code} = $expanded;
}
close(IN);

%abbrev_dir = (
	"11" => "North",
	"12" => "South",
	"13" => "East",
	"14" => "West",
	"15" => "Northeast",
	"16" => "Northwest",
	"17" => "Southeast",
	"18" => "Southwest",
	"19" => "Norte",
	"20" => "Sur",
	"21" => "Eeste",
	"22" => "Oeste",
	"23" => "Noreste",
	"24" => "Noroeste",
	"25" => "Sudeste",
	"26" => "Sudoeste",
);

%abbrev_qual = (
	"11" => "Access",
	"12" => "Alternate",
	"13" => "Business",
	"14" => "Bypass",
	"15" => "Connector",
	"16" => "Extended",
	"17" => "Extension",
	"18" => "Historic",
	"19" => "Loop",
	"20" => "Old",
	"21" => "Private",
	"22" => "Public",
	"23" => "Scenic",
	"24" => "Spur",
	"25" => "Ramp",
	"26" => "Underpass",
	"27" => "Overpass",
);

if ($#ARGV >= 0) {
	@counties = @ARGV;
} else {
	@counties = (
		"18011", # Boone
		"18057", # Hamilton
		"18023", # Clinton
		"18159", # Tipton
	);
}

print <<EOF
SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
BEGIN;
CREATE TABLE "tiger" (gid serial PRIMARY KEY,
"age" varchar(20),
"class" varchar(20),
"fullname" varchar(100));
SELECT AddGeometryColumn('','tiger','geom','0','MULTILINESTRING',2);
COMMIT;
EOF
;

%old = ();
%new = ();
%dup = ();
%lats = ();
%lons = ();

%kind = ();
%name = ();
%points = ();
%class = ();
$edgecount = 0;

$maxname = 23;

for $county (@counties) {
	print STDERR "county $county\n";

	open(IN, "java dbfcat tiger/www2.census.gov/geo/tiger/TIGER2013/FEATNAMES/tl_2013_${county}_featnames.zip |");
	$_ = <IN>;
	chomp;
	@columns = split(/\|/);
	while (<IN>) {
		chomp;
		@d = split(/\|/);

		%field = ();
		for ($i = 0; $i <= $#d; $i++) {
			# print "$i $columns[$i] $d[$i]\n";
			$d[$i] =~ s/^ *//;
			$d[$i] =~ s/ *$//;
			$field{$columns[$i]} = $d[$i];
		}

		$name = 
			"$abbrev_dir{$field{'PREDIR'}} " .
			"$abbrev_typ{$field{'PRETYP'}} " .
			"$abbrev_qual{$field{'PREQUAL'}} " .
			"$field{'NAME'} " .
			"$abbrev_dir{$field{'SUFDIR'}} " .
			"$abbrev_typ{$field{'SUFTYP'}} " .
			"$abbrev_qual{$field{'SUFQUAL'}} ";

		$name =~ s/ +/ /g;
		$name =~ s/^ *//;
		$name =~ s/ *$//;

		if ($name ne "")  {
			if ($featname{$field{'TLID'}}{$field{'PAFLAG'}} eq "") {
				$featname{$field{'TLID'}}{$field{'PAFLAG'}} = $name;
			} else {
				$featname{$field{'TLID'}}{$field{'PAFLAG'}} .= ";$name";
			}
		}

		# print "$field{'TLID'} => $featname{$field{'TLID'}}\n";
	}
	close(IN);

	open(IN, "java shpcat tiger/www2.census.gov/geo/tiger/TIGER2013/EDGES/tl_2013_${county}_edges.zip |");
	while (<IN>) {
		chomp;

                ($state, $cty, $tlid, $tfidl, $tfidr, $mtfcc, $fullname, $smid, $addrls, $addrle, $addrrs, $addrre) = split(/\|/);
		next unless ($mtfcc =~ /^S/ || $mtfcc =~ /R/); # roads, railroads

		next unless /polyline/;
		s/.*polyline //;

		@points = split(/ /, $_);

		$fullname =~ s/ *$//;
		$fullname =~ s/ +/ /g;

		$tlid =~ s/^ *//;
		$tlid =~ s/ *$//;

		if (defined $featname{$tlid}) {
			if (defined $featname{$tlid}{'A'} && length("$featname{$tlid}{'P'};$featname{$tlid}{'A'}") <= $maxname) {
				$fullname = "$featname{$tlid}{'P'};$featname{$tlid}{'A'}";
			} elsif (length($featname{$tlid}{'P'}) <= $maxname) {
				$fullname = $featname{$tlid}{'P'};
			}
		}

		$fullname =~ s/'/''/g;

		$edgecount++;
		$kind{$edgecount} = "new";
		$name{$edgecount} = $fullname;
		$class{$edgecount} = $mtfcc;
		# $file{$edgecount} = $file;

		for ($i = 0; $i < $#points; $i++) {
			($lon1, $lat1) = split(/,/, $points[$i]);
			($lon2, $lat2) = split(/,/, $points[$i + 1]);

			$lat1 = sprintf("%.5f", $lat1);
			$lon1 = sprintf("%.5f", $lon1);
			$lat2 = sprintf("%.5f", $lat2);
			$lon2 = sprintf("%.5f", $lon2);

			if ($i == 0) {
				push @{$points{$edgecount}}, "$lon1 $lat1";
			}

			push @{$points{$edgecount}}, "$lon2 $lat2";
			@p = sort("$lon1 $lat1", "$lon2 $lat2");
			$new{"$p[0] $p[1]"} = 1;
		}
	}
	close(IN);
}

for $county (@counties) {
	print STDERR "old county $county\n";

	$state = substr($county, 0, 2);
	$statename = $state_number_map{$state};
	$file = "tiger/www2.census.gov/geo/tiger/tiger2006se/$statename/TGR${county}.ZIP";

	open(IN, "unzip -p $file TGR$county.RT2 |");
	while (<IN>) {
		chomp;
		$tlid = substr($_, 5, 10);
		$tlid =~ s/^ *//;

		for ($i = 18; $i < 208; $i += 19) {
			$lon = sprintf("%.5f", substr($_, $i, 10) / 1000000);
			$lat = sprintf("%.5f", substr($_, $i + 10, 9) / 1000000);

			if ($lat != 0) {
				push @{$lats{$tlid}}, $lat;
				push @{$lons{$tlid}}, $lon;
			}
		}
	}
	close(IN);

	open(IN, "unzip -p $file TGR$county.RT1 |");
	while (<IN>) {
		chomp;
		$tlid = substr($_, 5, 10);
		$tlid =~ s/^ *//;

		$class = substr($_, 55, 3);
		next unless ($class =~ /^A/ || $class =~ /B/); # roads, railroads

		$startlon = sprintf("%.5f", substr($_, 190, 10) / 1000000);
		$startlat = sprintf("%.5f", substr($_, 200, 9) / 1000000);
		$endlon = sprintf("%.5f", substr($_, 209, 10) / 1000000);
		$endlat = sprintf("%.5f", substr($_, 219, 9) / 1000000);

		$fullname = substr($_, 17, 2 + 30 + 4 + 2);
		$fullname =~ s/^ *//;
		$fullname =~ s/ *$//;
		$fullname =~ s/ +/ /g;
		$fullname =~ s/'/''/g;

		unshift @{$lats{$tlid}}, $startlat;
		unshift @{$lons{$tlid}}, $startlon;

		push @{$lats{$tlid}}, $endlat;
		push @{$lons{$tlid}}, $endlon;

		@lats = @{$lats{$tlid}};
		@lons = @{$lons{$tlid}};

		$edgecount++;
		$kind{$edgecount} = "old";
		$name{$edgecount} = $fullname;
		$class{$edgecount} = $class;
		# $file{$edgecount} = $file;

		for ($i = 0; $i < $#lats; $i++) {
			if ($i == 0) {
				push @{$points{$edgecount}}, "$lons[$i] $lats[$i]";
			}

			push @{$points{$edgecount}}, "$lons[$i + 1] $lats[$i + 1]";
			@p = sort("$lons[$i] $lats[$i]", "$lons[$i + 1] $lats[$i + 1]");
			$old{"$p[0] $p[1]"} = 1;
		}
	}
	close(IN);
}

{
	print "BEGIN;\n";

	for $n (keys(%new)) {
		if ($old{$n}) {
			$dup{$n} = 1;
		}
	}

	for ($i = 0; $i < $edgecount; $i++) {
		@points = @{$points{$i}};

		for ($j = 0; $j < $#points; $j++) {
			@p = sort($points[$j], $points[$j + 1]);
			$kind = $kind{$i};

			if ($dup{"$p[0] $p[1]"}) {
				$kind = "both";

				if ($used{"$p[0] $p[1]"}) {
					$kind = "used";
				} else {
					$used{"$p[0] $p[1]"} = 1;
				}
			}

			if ($within ne "" && $within ne $kind) {
				print "))');\n";
				$within = "";
			}

			if ($kind ne "used") {
				if ($within eq "") {
					print "INSERT INTO \"tiger\" (\"age\",\"class\",\"fullname\",geom) ";
					print "VALUES ('$kind','$class{$i}','$name{$i}',";
					print "'MULTILINESTRING((";

					print "$points[$j]";
					$within = $kind;
				}

				print ", $points[$j + 1]";
			}
		}

		if ($within ne "") {
			print "))');\n";
			$within = "";
		}
	}

	print "COMMIT;\n";
}
