#!/bin/bash

mkdir -p county-delta-2006-2014

./get-county-delta-2006-2014 $(cat fips-special) > county-delta-2006-2014/special

comm -23 <(
	ls /data/data/tiger/2014/www2.census.gov/geo/tiger/TIGER2014/ROADS/tl_2014_* |
	sed 's/.*tl_2014_//' |
	sed 's/_roads.zip//' |
	sort
) <(
	cat fips-special
) |
xargs -P 8 -n 1 ./get-county-delta-wrap-2006-2014
