#!/bin/sh

alaska=$(
	(
		ls tiger/www2.census.gov/geo/tiger/tiger2006se/AK/ |
		grep TGR |
		sed 's/.*TGR//' |
		sed 's/.ZIP//'

		ls tiger/www2.census.gov/geo/tiger/TIGER2013/EDGES/tl_2013_02* |
		sed 's/.*2013_//' |
		sed 's/_edges.zip//'
	) | sort | uniq
)

./get-county-delta2 $alaska > county-delta/alaska

find tiger/www2.census.gov/geo/tiger/tiger2006se/ |
grep TGR |
sed 's/.*TGR//' |
sed 's/.ZIP//' |
grep -v '^02' |
sort |
xargs -P 8 -n 1 ./get-county-delta-wrap2
