#!/usr/bin/perl

open(IN, "abbreviations.tab");
while (<IN>) {
	if (/Direction Code    Expanded Full Text   Directional Abbreviation   Spanish   Translation/) {
		while (<IN>) {
			chomp;
			last if /^$/;

			($code, $text, $abbrev, $spanish, $translation) = split(/  +/);

			if ($spanish ne "Y") {
				$abbrev{'PREDIRABRV'}{$abbrev} = $text;
				$abbrev{'SUFDIRABRV'}{$abbrev} = $text;
			}
		}
	}

	if (/Qualifier Code   Expanded Full Text   Display Name Abbreviation   Prefix Qualifier   Suffix Qualifier/) {
		while (<IN>) {
			chomp;
			last if /^$/;

			($code, $text, $abbrev, $prefix, $suffix) = split(/  +/);
			if ($prefix eq "Y") {
				$abbrev{'PREQUALABR'}{$abbrev} = $text;
			}
			if ($suffix eq "Y") {
				$abbrev{'SUFQUALABR'}{$abbrev} = $text;
			}
		}
	}

	if (/Type Code    Expanded Full Text   Display Name abbreviation   Spanish   Translation          Prefix Type   Suffix/) {
		while (<IN>) {
			chomp;
			last if /^$/;

			($code, $text, $abbrev, $spanish, $translation, $prefix, $suffix) = split(/  +/);

			if ($spanish ne "Yes") {
				$prefix = $spanish;
				$suffix = $translation;

				$spanish = "";
				$translation = "";
			}

			if ($prefix eq "Y") {
				$abbrev{'PRETYPABRV'}{$abbrev} = $text;
			}
			if ($suffix eq "Y") {
				$abbrev{'SUFTYPABRV'}{$abbrev} = $text;
			}
		}
	}
}
close(IN);

if (0) {
	for $a (sort(keys(%abbrev))) {
		for $b (sort(keys(%{$abbrev{$a}}))) {
			print "$a $b => $abbrev{$a}{$b}\n";
		}
	}
}

$_ = <>;
chomp;
@fields = split(/\|/, $_);

for ($i = 0; $i <= $#fields; $i++) {
	# print "map: $fields[$i] -> $i\n";
	$map{$fields[$i]} = $i;
}

while (<>) {
	chomp;
	@fields = split(/\|/, $_);

	# for $field ('PREDIR', 'PREDIRABRV', 'PRETYP', 'PRETYPABRV', 'PREQUAL', 'PREQUALABR', 'NAME', 'SUFDIR', 'SUFDIRABRV', 'SUFTYP', 'SUFTYPABRV', 'SUFQUAL', 'SUFQUALABR') {

	$out = "";
	for $field ('PREDIRABRV', 'PRETYPABRV', 'PREQUALABR', 'NAME', 'SUFDIRABRV', 'SUFTYPABRV', 'SUFQUALABR') {
		$t = $fields[$map{$field}];
		$t =~ s/ *$//;

		if ($abbrev{$field}{$t} ne "") {
			$t = $abbrev{$field}{$t};
		}

		$out .= "$t ";
	}

	$out =~ s/^ *//;
	$out =~ s/ *$//;
	$out =~ s/ +/ /g;

	$fn = $fields[$map{'FULLNAME'}];
	$fn =~ s/ *$//;

	if ($fn ne $out) {
		if (!$seen{$fn}) {
			print "$fn|$out\n";
			$seen{$fn} = 1;
		}
	}
}
