#!/bin/sh

dropdb -U postgres tigerchanges
createdb -U postgres -T template_postgis tigerchanges

./get-county-delta2 ${1+"$@"} | psql -U postgres tigerchanges

echo "CREATE INDEX tiger_geom ON tiger USING GIST(geom);" | psql -U postgres tigerchanges

