#!/bin/sh

db=tigerdelta

dropdb -U postgres $db
createdb -U postgres -T template_postgis $db

./get-county-delta2 ${1+"$@"} | psql -U postgres $db

echo "CREATE INDEX tiger_geom ON tiger USING GIST(geom);" | psql -U postgres $db

