#!/bin/sh

dropdb -U postgres tigerdelta
createdb -U postgres -T template_postgis tigerdelta

./get-county-delta2 ${1+"$@"} | psql -U postgres tigerdelta

echo "CREATE INDEX tiger_geom ON tiger USING GIST(geom);" | psql -U postgres tigerdelta

