#!/usr/bin/perl

sub out {
	@s = sort { $a <=> $b } keys(%where);
	return if $#s < 0;

	print '{ "type": "Feature", "properties": { ';
	print "\"name\": \"$oname\", \"way\": $oway";
	print ' }, "geometry": { "type": "LineString", "coordinates": [';

	for ($i = 0; $i <= $#s; $i++) {
		if ($i == 0) {
			# first
		} elsif ($s[$i] ne $s[$i - 1] + 1) {
			# restarting after gap

			print "] } }\n";
			print '{ "type": "Feature", "properties": { ';
			print "\"name\": \"$oname\", \"way\": $oway";
			print ' }, "geometry": { "type": "LineString", "coordinates": [';
		} else {
			# continuing

			($lat1, $lon1, $lat2, $lon2) = split(/[:,]/, $where{$s[$i]});
			print ", [ $lon2, $lat2 ]";
			next;
		}

		($lat1, $lon1, $lat2, $lon2) = split(/[:,]/, $where);
		print "[ $lon1, $lat1 ], [ $lon2, $lat2 ]";
	}

	print "] } }\n";
	$within = 1;
}


while (<>) {
	chomp;

	($where, $kind, $slash, $way, $seg, $name) = split(/ /, $_, 6);

	$name =~ s/"//g;
	$name =~ s/_/ /g;
	$name =~ s/\\/\\\\/g;

	if ($way ne $oway) {
		out();

		%where = ();
	}

	$oname = $name;
	$oway = $way;

	$where{$seg} = $where;
}

out();

